<?php
/**
 * View script for rendering the key pair generation form
 */

$this->headTitle('Manual Text Encryption/Decryption');

?>

<div class="page-header">
	<h1>Manual Text Encryption/Decryption</h1>
</div>

<?php echo $this->partial('netglue-encrypt/top'); ?>

<?php
if(isset($this->error) && true === $this->error) {
?>
	<div class="alert alert-block alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<h4>Form Errors</h4>
		<p>Please review the error messsages below and adjust your input accordingly</p>
	</div>
<?php
}

if($this->result) {
	?>
	<div class="well">
		<h2>Encrypted/Decrypted Output</h2>
		<textarea rows="15" class="input-block-level"><?php
		echo $this->escapeHtml($this->result);
		?></textarea>
	</div>
	<?php
}
?>

<div class="row">
	<div class="span8">
		<div class="well">
		<?php

		$this->form->setAttribute('class', 'form-horizontal');
		echo $this->form()->openTag($this->form);

		foreach($this->form as $element) {
	
			if($element instanceof \Zend\Form\Element\Textarea) {
				$element->setAttribute('class', 'input-block-level');
				$element->setAttribute('rows', 15);
			}
	
			if($element instanceof \Zend\Form\Element\Button) {
				?>
				<div class="form-actions">
					<?php
					$element->setAttribute('class', 'btn btn-primary');
					echo $this->formButton($element); ?> 
					<button type="reset" class="btn">Reset</button>
				</div>
				<?php
			} elseif($element instanceof \Zend\Form\Element\Hidden) {
				echo $this->formHidden($element);
			} else {
				?>
		
				<div class="control-group">
					<?php
					echo $this->formLabel()->openTag(array('for' => $element->getAttribute('name'), 'class' => 'control-label'));
					echo $this->escapeHtml($element->getLabel());
					echo $this->formLabel()->closeTag();
					?>
					<div class="controls">
						<?php
						echo $this->formElement($element);
						$this->formElementErrors()->setAttributes(array('class' => 'text-error unstyled'));
						echo $this->formElementErrors($element);
						?>
					</div>
				</div>
		
				<?php
			}
		}

		echo $this->form()->closeTag($this->form);
		
		?>
		</div>
	</div>
	
	<div class="span4">
		<div class="well">
			<h4>Manual Encryption/Decryption</h4>
			<p><strong>For encryption</strong>, simply select the key pair
			you wish to use, paste into the input text field the data you
			want encrypted and hit submit. There is no need to provide the
			pass phrase for encryption, this is only required for decryption
			with keys that require a pass phrase.</p>
			<p>To decrypt information, the key pair you select must match
			the key that was used to encrypt the data in the first place. You
			will likely want the output to be Base64 encoded and if the
			selected key requires a password and it has not already been set
			you will need to enter that too.</p>
		</div>
	</div>
</div>
